export const CREATE_GROUP = "CREATE_GROUP";
export const UPDATE_GROUP = "UPDATE_GROUP";
export const DELETE_GROUP = "DELETE_GROUP";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const GET_ACCOUNT = "GET_ACCOUNT";
export const GET_ACCOUNTS_BY_GROUP = "GET_ACCOUNTS_BY_GROUP";

export const GET_STATUSES = "GET_STATUSES";
export const GET_TODO = "GET_TODO";
export const GET_TODOS_BY_GROUP = "GET_TODOS_BY_GROUP";
export const GET_TODOS_BY_ACCOUNT = "GET_TODOS_BY_ACCOUNT";
export const CREATE_TODO = "CREATE_TODO";
export const UPDATE_TODO = "UPDATE_TODO";
export const DELETE_TODO = "DELETE_TODO";

export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";
export const DELETE_ALL_NOTIFICATIONS = "DELETE_ALL_NOTIFICATIONS";
